version: '3.8'

services:
  api:
    build: ./api
    command: flask run -h 0.0.0.0
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - custom-network

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=serge
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=file_storage
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge

volumes:
  postgres_data: